name: CD - Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Build Docker Image
      run: docker build -t myapi:latest .

    - name: Save Docker Image
      run: docker save myapi:latest -o myapi.tar

    - name: Copy to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        source: "myapi.tar"
        target: "/home/${{ secrets.SERVER_USER }}/"

    - name: Deploy on Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        script: |
          docker load -i myapi.tar
          docker stop myapi || true
          docker rm myapi || true
          docker run -d -p 80:80 --name myapi myapi:latest
